### ISSUE TITLE
scalac error: bad option: '-make:transitive'

### ISSUE THREAD

**Issue by polentino** [davidB/scala-archetype-simple#21]
On a completely new maven project, running **mvn compile** will produce the following error: 

> [ERROR] scalac error: bad option: '-make:transitive'

Thus, the line 
`<arg>-make:transitive</arg>`
shoul be removed from the pom file.

**Comment by libasoles** [comment]
That was treated here: https://github.com/davidB/scala-archetype-simple/issues/8
And merged here: https://github.com/davidB/scala-archetype-simple/pull/11

See, the line is not there anymore:
https://github.com/davidB/scala-archetype-simple/blob/master/src/main/resources/archetype-resources/pom.xml

However, I'm facing the same problem than you. Now sure why!. See, I'm using the archetype like this:

`mvn archetype:generate -B -DarchetypeGroupId=net.alchim31.maven -DarchetypeArtifactId=scala-archetype-simple -DarchetypeVersion=1.6 -DgroupId=com.dada -DartifactId=scala-dada -Dversion=0.1-SNAPSHOT`

That's the latest version, 1.6, so what's wrong?

Did you already solve this @polentino ?

**Comment by polentino** [comment]
@libasoles sorry for the late reply. Of course we're both facing this problem: #11 was merged on Dec 5, 2015 but the latest version of the archetype, 1.6, dates back to [June 07, 2015](https://mvnrepository.com/artifact/net.alchim31.maven/scala-archetype-simple/1.6).

@davidB , are  there any plans for an updated version of the archetype?

**Comment by M3ssman** [comment]
Anything new regarding this issue? I'm too facing same problem using V1.6?

**Comment by davidB** [comment]
I had issue to sign with gpg + maven on my current computer. I should be able restore my old computer next week-end and to release a new version.

Sorry for delay.

**Comment by davidB** [comment]
Should be fixed with 1.7
