### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mbonaci** [davidB/scala-archetype-simple#7]
Hi David,
would you be so kind to include a LICENSE.md in your repo?
I need to fork your repo (already did) so I can set up Apache Spark archetype (already did).
It's for the [book I'm writing](https://github.com/spark-in-action/scala-archetype-sparkinaction), so I need to be careful and 100% legally clear and the only way is to have an explicit license.

I'll understand if you include a restrictive license which will preclude me from doing so.

BTW I included your version history in CHANGES.md.

Thanks

**Comment by davidB** [comment]
Hi,

Ok, I'll include the 2 files next WE. License of the archetype will be CC0, so it should be fine for any derivative work.

**Comment by mbonaci** [comment]
Thanks, great!
Your archetype was very useful to me.
Are you interested at all in Apache Spark?
I might be able to sneak one out when the MEAP goes out :)
If yes, please provide me your e-mail.

**Comment by mbonaci** [comment]
Very nice of you, thanks :+1:

**Comment by davidB** [comment]
np. I'm happy when some of my stuff is usefull.

I'm interested by your book. Currently, I'm reading doc about Samza. My email is in the commit log of your fork (only remove +gravatar). And your book could be usefull for a future job ;-)

Thanks.

**Comment by mbonaci** [comment]
I'll be glad to do that.
Expect e-mail from Manning with a complimentary copy in the next week or two.

**Comment by burgerdev** [comment]
The license information in `LICENSE.md` (CC0) is not compatible with the license statement in `src/main/resources/archetype-resources/src/test/scala/samples/scalatest.scala` (Apache License). Could you please clarify this?

**Comment by mbonaci** [comment]
@burgerdev scalatest is a separate ["product"](http://www.scalatest.org/about), which is licensed under Apache 2.0.
