### ISSUE TITLE
-make:transitive not playing nice with Scala 2.11

### ISSUE THREAD

**Issue by duffj** [davidB/scala-archetype-simple#8]
The archectype `pom.xml` file currently contains the following code (part of the configuration of the `scala-maven-plugin`:

    <arg>-make:transitive</arg>

This argument no longer works since 2.11 (see [stackoverflow](http://stackoverflow.com/questions/23875515/compilation-error-in-scala) for more info). This caused my "Hello World" application to fail to compile out of the box. Should it be removed from the archetype? If so, I'm happy to submit a PR.

**Comment by davidB** [comment]
PR for a 2.11 archetype is welcome.
